name = "leternet"
account_id = "9d1aa3bcce298960a2fc322768d4f019"
compatibility_date = "2025-09-27"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = true

[assets]
directory = "./dist"

[[routes]]
pattern = "leter.net"
custom_domain = true
